dist: xenial

language: csharp
mono: none
dotnet: 3.1

git:
    depth: false

solution: SteamKit2/SteamKit2.sln

before_install:
    - sudo apt-get update
    - sudo apt-get install -y dotnet-runtime-2.1

install:
    - dotnet restore SteamKit2/SteamKit2.sln
    - dotnet restore Samples/Samples.sln

before_script:
    - export PATH="$PATH:/home/travis/.dotnet/tools"

script:
    - dotnet build SteamKit2/SteamKit2/SteamKit2.csproj
    - dotnet build SteamKit2/Tests/Tests.csproj
    - dotnet build Resources/SteamLanguageParser/SteamLanguageParser.csproj
    - dotnet build Samples/Samples.sln
    - dotnet test SteamKit2/Tests/Tests.csproj

notifications:
    irc:
        channels:
            - "irc.freenode.net#steamkit"
        on_success: never
        on_failure: always

cache:
    directories:
        - "~/.nuget/packages"
        - "~/.local/share/NuGet/Cache"
        - "~/.sonar/cache"
