version: 1.0.{build}-Alpha
os: Visual Studio 2015

cache:
  - '%LocalAppData%\NuGet\Cache'
  - '%Temp%\nethook2-dependencies -> Resources\NetHook2\SetupDependencies.ps1'

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_informational_version: "{version} - CI (AppVeyor)"

configuration:
  - Debug
  - Release

environment:
  SK_BUILD_CONFIGURATION: $(configuration)

init:
  - git config --global core.autocrlf true

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  - nuget restore SteamKit2\SteamKit2.sln
  - nuget restore Samples\Samples.sln
  - Resources\NetHook2\SetupDependencies.cmd

build_script:
  - msbuild SteamKit2\SteamKit2.sln
  - msbuild Samples\Samples.sln
  - msbuild Resources\NetHook2\NetHook2.sln
  - msbuild Resources\NetHookAnalyzer2\NetHookAnalyzer2.sln

after_build:
  - '7z a NetHook2.zip .\Resources\NetHook2\%SK_BUILD_CONFIGURATION%\*.dll .\Resources\NetHook2\%SK_BUILD_CONFIGURATION%\*.pdb'
  - ps: >-
      $args = @('pack', 'SteamKit2\SteamKit2.nuspec')
      $version = $null
      if (Test-Path Env:APPVEYOR_REPO_TAG_NAME)
      {
        $version = (Get-Item Env:APPVEYOR_REPO_TAG_NAME).Value
      }
      
      if (![string]::IsNullOrEmpty($version))
      {
          $args += $('-Version', $version)
      }
      & nuget $args

test_script:
  - ps: >-
      $TestAssembly = "SteamKit2\Tests\Bin\$env:SK_BUILD_CONFIGURATION\Tests.dll"
      
      if (Test-Path $TestAssembly)
      {
          & nuget install OpenCover -Version 4.6.166 -OutputDirectory SteamKit2\packages
          & SteamKit2\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user "-target:xunit.console.clr4.exe" "-targetargs:$TestAssembly /noshadow /appveyor" -returntargetcode "-filter:+[SteamKit2]* -[SteamKit2]SteamKit2.Internal.* -[SteamKit2]SteamKit2.*.Internal.* -[SteamKit2]SevenZip*" "-excludebyattribute:*.ProtoContract*" -hideskipped:All -output:SteamKit2-code-coverage.xml
          $env:Path = "C:\Python34;C:\Python34\Scripts;" + $env:Path
          & pip install codecov
          & codecov -f "SteamKit2-code-coverage.xml" -X gcov
      }

artifacts:
  - path: NetHook2.zip
    name: NetHook2
  - path: '**\*.nupkg'
    name: 'NuGet Package'
  - path: 'Resources\NetHookAnalyzer2\Bin\$(configuration)'
    name: 'NetHook Analyzer 2'

deploy:
  - provider: NuGet
    api_key:
      secure: 'Qtxl16gv6dxg4FXOPLiNkLkTuVdPcso3IS99WgRO7IXyqgLJQJ3Ldrnymai2+1Uo'
    skip_symbols: false
    artifact: 'NuGet Package'
    on:
      #branch: master
      configuration: Release
      appveyor_repo_tag: true
  - provider: GitHub
    auth_token:
      secure: 'KEOYmhFMh4Ea7RVYmX1Sv/1SWQW5uoNv6p3+aUtJXw/2Vbp2PEmbJxYJxO9xIuc9'
    release: 'SteamKit2 $(appveyor_repo_tag_name)'
    artifact: 'NuGet Package, NetHook Analyzer 2'
    draft: false
    prerelease: true
    on:
      #branch: master
      configuration: Release
      appveyor_repo_tag: true
